name: Publish Java Package

on:
  push:
    branches:
      - main  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 with Maven settings
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }} # Using the provided GITHUB_TOKEN

      - name: permission mvnw
        run: chmod +x ./mvnw
        
      - name: Build with Maven
        run: ./mvnw clean package -B

      # This step might not be necessary if Maven is configured to authenticate using the setup-java action
      - name: Log in to GitHub Packages (if needed for CLI operations)
        if: steps.setup-java.outputs.settings-path # Only run if the setup-java step was successful
        run: echo "${{ secrets.TOKEN }}" | gh auth login --with-token

      - name: Publish to GitHub Packages
        run: ./mvnw deploy -Dmaven.test.skip=true -DuniqueVersion=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GITHUB_TOKEN for Maven authentication as well
